{{- if .Values.iamStaffUi.enabled }}
{{- $values := .Values.iamStaffUi -}}
{{- $context := dict "Values" (merge (deepCopy $values) (dict "global" .Values.global)) "Chart" .Chart "Release" .Release "Files" .Files "Capabilities" .Capabilities -}}
{{- with $context -}}
{{- if and .Values.istio.enabled .Values.istio.virtualservice.enabled }}
{{- $hostname := include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.host "context" $) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: iam-staff-ui
spec:
  hosts:
  - {{ $hostname | quote }}
  gateways:
  - {{ default (include "common.names.fullname" .) .Values.istio.virtualservice.gateway }}
  http:
  - headers:
      request:
        set:
          x-forwarded-host: {{ $hostname | quote }}
          x-forwarded-proto: https
    match:
    - uri:
        prefix: {{ .Values.istio.virtualservice.prefix | default "/" }}
    route:
    - destination:
        {{- if .Values.istio.virtualservice.destination }}
        host: {{ include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.destination "context" $) }}
        {{- else }}
        host: {{ include "common.names.fullname" . }}
        {{- end }}
        port:
          number: {{ include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.destinationPort "context" $) }}
{{- end }}
{{- end -}}
{{- end }}
